### ISSUE TITLE
Improvements Needed for Better Code Management and Readability

### ISSUE THREAD

**Issue by Esh07** [soniyaprasad77/soniyaprasad77.github.io#11]
### **Is your feature request related to a problem? Please describe.**

I recently came across your repository and noticed a few areas that could be improved for better code management and readability:
1. **Folder Structure**: The repository currently lacks a clear folder structure. Having a well-defined folder structure makes it easier for contributors to locate files and understand the flow of the code.

2. **.gitignore File**: There is no `.gitignore` file in the repository. This file is important to avoid committing unnecessary files to the repo (like .log, .cache .DS_STORE, etc.).

3. **File Names**: Some of the file names are not clear (e.g., 'istockphoto-903044512-170667a.jpg', '7ca7cd84-b514-4d79-862a-3b7f508e31eb.png' etc). It would be helpful if the files were named in a more descriptive way, following a consistent naming convention.

4. **Link Paths**: The repository currently uses absolute paths for links. This could lead to broken links if the URL of your profile changes or if the project is moved to another repository under a different name. It's recommended to use relative paths instead.
    - See this code line 16 on file `index.html`: 
        - Favicon Img https://github.com/soniyaprasad77/soniyaprasad77.github.io/blob/a67ab1aef57f2641d51ede941be0b6e91054c10a/index.html#L14-L18
        - Logo img https://github.com/soniyaprasad77/soniyaprasad77.github.io/blob/a67ab1aef57f2641d51ede941be0b6e91054c10a/index.html#L28-L31
        - Profile photo https://github.com/soniyaprasad77/soniyaprasad77.github.io/blob/a67ab1aef57f2641d51ede941be0b6e91054c10a/index.html#L63-L65
        - PDF FIle https://github.com/soniyaprasad77/soniyaprasad77.github.io/blob/a67ab1aef57f2641d51ede941be0b6e91054c10a/index.html#L263-L268

### **Describe the solution you'd like**
I suggest the following solutions to above mentioned issues:
1. **Static Files**: 
I noticed that static files such as `.js`,`.css` and favicon icons are currently in the root directory. It would be more efficient to store these in a `static/` directory. Inside the `static/` directory, you could create sub-directories for each type of file (e.g., a `js/` folder for JavaScript files and a `css/` folder for CSS files). Given that your portfolio doesn't have multiple JavaScript or CSS files, it's fine to create only one folder and store these files into `static` folder. 

2. **Media Files**: 
Similarly, media files like images and PDFs could be moved into a `media/` directory. Inside the `media/` directory, you can create sub-folders for different types of media (e.g., an `images/` or `img/` folder for images and a `doc/` folder for PDFs).

3. **.gitignore File**: 
Visit [gitignore.io](https://www.gitignore.io) and enter the types of files you want to ignore (e.g., Windows, macOS, Linux, VisualStudioCode). This site generates a `.gitignore` file that helps GitHub ignore certain hidden files that are not necessary to track, such as the `.DS_STORE` file often generated on macOS. Adding this .gitignore file to your repository will prevent these types of files from being tracked by Git.
    - In my recommendation, I've covered most of the IDEs used for web development. You can copy-paste from [this link](https://www.toptal.com/developers/gitignore/api/linux,macos,windows,visualstudiocode,git,eclipse,dreamweaver,sublimetext,pycharm,intellij,webstorm,netbeans,notepadpp,xcode,emacs,nova)
        1. Create a `.gitignore` file in the root folder of your project.
         2. Copy and paste the content generated from the link into the `.gitignore` file.
         3. Use the following git commands to add, commit, and push your changes:

         ```bash
         git add .gitignore
         git commit -m "Added .gitignore file"
         git push

4. **Link Paths**: 
Review the code and convert all absolute paths to relative paths. For example, if there's a link to an image like `https://raw.githubusercontent.com/soniyaprasad77/soniyaprasad77.github.io/main/logo.png`, it should be changed to `./static/logo/logo.svg` (assuming the HTML file is in the root directory and you've `static/logo` folder where logo is stored).
This approach ensures that the links will continue to work correctly, even if the profile link updates or the project is moved to another repository under a different name.


### **Additional context**
Given the number of improvements suggested, this issue could be considered a "mega issue". To make it more manageable, I recommend breaking it down into smaller sub-issues, each targeting a specific improvement.  (for better understanding, refer [Github Doc on task list](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#about-issue-task-lists))

Here's a possible breakdown:

- [x] #15
- [x] #16
- [x] #17
- [x] #18

Each sub-issue can be tracked with a task list in this mega issue. As each sub-issue is resolved, its corresponding task can be checked off. This approach will make it easier to track progress and keep the project organised.

I hope these suggestions are helpful!

Happy coding 
💯

**Comment by Sushannt** [comment]
Hi @soniyaprasad77  please assign me this under hacktoberfest-accepted label

**Comment by Esh07** [comment]
Go ahead and pick either the one issue as mentioned in the description @Sushannt .
