### ISSUE TITLE
ImprovIsing the contact me section

### ISSUE THREAD

**Issue by Manideep711** [soniyaprasad77/soniyaprasad77.github.io#13]
when user hovers the email section  the effect should get as previous My project one
![image](https://github.com/soniyaprasad77/soniyaprasad77.github.io/assets/125902846/978de5ad-36a2-4377-a15c-2444f80fe773)
![image](https://github.com/soniyaprasad77/soniyaprasad77.github.io/assets/125902846/16b4d5a8-607f-4647-b1bb-b62e65abc438)

**Comment by soniyaprasad77** [comment]
No, its intentionally not taken, because its a text field, using such colors is not useful. Thankyou
