### ISSUE TITLE
[low, good-first-issue] Add `.gitignore` file to project

### ISSUE THREAD

**Issue by Esh07** [soniyaprasad77/soniyaprasad77.github.io#16]
## Issue
There is no `.gitignore` file in the repository. This file is important to avoid committing unnecessary files to the repo (like .log, .cache .DS_STORE, etc.).

## Possible solution
Visit [gitignore.io](https://www.gitignore.io) and enter the types of files you want to ignore (e.g., Windows, macOS, Linux, VisualStudioCode). This site generates a `.gitignore` file that helps GitHub ignore certain hidden files that are not necessary to track, such as the `.DS_STORE` file often generated on macOS. Adding this .gitignore file to your repository will prevent these types of files from being tracked by Git.
- In my recommendation, I've covered most of the IDEs used for web development. You can copy-paste from [this link](https://www.toptal.com/developers/gitignore/api/linux,macos,windows,visualstudiocode,git,eclipse,dreamweaver,sublimetext,pycharm,intellij,webstorm,netbeans,notepadpp,xcode,emacs,nova)
    1. Create a `.gitignore` file in the root folder of your project.
     2. Copy and paste the content generated from the link into the `.gitignore` file.
     3. Use the following git commands to add, commit, and push your changes:
      
    ```bash
         git add .gitignore
         git commit -m "Added .gitignore file"
         git push
    ```

**Comment by NipuniNuwanthika** [comment]
Hi, Please assign me this issue.
