### ISSUE TITLE
[High, good-first-issue] Improve file naming convention

### ISSUE THREAD

**Issue by Esh07** [soniyaprasad77/soniyaprasad77.github.io#17]
## Issue 
Some of the file names are not clear (e.g., `istockphoto-903044512-170667a.jpg`, `7ca7cd84-b514-4d79-862a-3b7f508e31eb.png` etc). It would be helpful if the files were named in a more descriptive way, following a consistent naming convention.

## Possible Solution
Rename the file names to be descriptive and short such as if it logo png file then for example keep the name `logo.png`. Similarly, if it profile photo or PDF file then give good descriptive name like `profile-xs-screen.png` for smaller screen or resume.pdf respectively.

**Comment by c4coderandcreator** [comment]
assign this to me
