### ISSUE TITLE
implement a navbar that stick to the screen throughout the page

### ISSUE THREAD

**Issue by chendjou237** [soniyaprasad77/soniyaprasad77.github.io#3]
I hope you're well. I'd like to request permission to work on a sticky navbar feature for our repository. This enhancement will keep the navbar at the top of the screen as users scroll, improving user experience and navigation.

Here's what you can expect from this implementation:

User Experience: Enhanced navigation and improved user engagement.
Compatibility: Extensive testing to ensure cross-browser and responsive compatibility.
Accessibility: Adherence to accessibility standards for a wider user base.
Performance: Careful optimization to prevent performance issues.
I'm ready to create a dedicated branch, develop the feature, and submit pull requests for review. Your guidance and any specific requirements you have are highly valued.

Looking forward to your response.

**Comment by chendjou237** [comment]
can you add the label for the hacktober fest on the issue

**Comment by soniyaprasad77** [comment]
Once the issue is resolved, I'll go ahead and apply the "hacktoberfest-accepted" label. Thank you for your cooperation.

**Comment by MrDBC** [comment]
can i work on the issue? @soniyaprasad77
