### ISSUE TITLE
improving projects ui

### ISSUE THREAD

**Issue by itsgeekhokage** [soniyaprasad77/soniyaprasad77.github.io#32]
view code and view projects are clickable events, i think they should be buttons

![Screenshot (168)](https://github.com/soniyaprasad77/soniyaprasad77.github.io/assets/100841132/fc4c8dca-4c46-49ac-b319-695afa9a5a04)

please assign me this issue @soniyaprasad77

**Comment by Prakharpandey007** [comment]
Please assign me this issue . I am interested to work on this issue.Looking for positive response.
thank you .
