### ISSUE TITLE
Add a contribution guide

### ISSUE THREAD

**Issue by VirginieLemaire** [soniyaprasad77/soniyaprasad77.github.io#4]
Hi 👋🏼 ,
To help new contributors to contribute to your project, you might:
- add a CONTRIBUTING file.md
- update README.md to link to this file

I'll be glad to do this for you as an Hacktoberfest contribution 😉

**Comment by soniyaprasad77** [comment]
Every Commit is Valuable, Go ahead and Thank-you for your valuable time.

**Comment by VirginieLemaire** [comment]
Thank you, PR is ready ;)

**Comment by soniyaprasad77** [comment]
Merged and Glad to have contributed.
