### ISSUE TITLE
First name and second name in two lines

### ISSUE THREAD

**Issue by Shybymh** [soniyaprasad77/soniyaprasad77.github.io#43]
The page has the first name and second name split in two lines. I want to work on it to make it visually more pleasing. Please assign it to me under hacktoberfest 2023
<img width="1428" alt="Screenshot 2023-10-18 at 1 27 11 PM" src="https://github.com/soniyaprasad77/soniyaprasad77.github.io/assets/97486205/a0f93768-75ac-4cd6-9ec7-716ec43e2ff5">

**Comment by soniyaprasad77** [comment]
This option is intentionally opted. Thankyou
