### ISSUE TITLE
Low Quality Laptop Images

### ISSUE THREAD

**Issue by micahyoung324** [soniyaprasad77/soniyaprasad77.github.io#44]
The [laptop background image on the homepage](https://github.com/soniyaprasad77/soniyaprasad77.github.io/blob/main/assets/images/Background-design-desktop.png) is noticeably low quality.

Is this image your or where did you get this from? Do you have any preference for the new image if you want me to find free photo version to replace? 

You could assign me under Hacktoberfest 2023 once we figure out the answer above. I have photoshop skills to use as well to edit for the same issue for [mobile version](https://github.com/soniyaprasad77/soniyaprasad77.github.io/blob/main/assets/images/Background-design-mobile.png).

Thanks!

**Comment by soniyaprasad77** [comment]
Oh wow intrigued by your suggestion!

**Comment by micahyoung324** [comment]
I found exact same photo [here](https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&q=80&w=1120&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D) but better quality.

I am going ahead and edit in photoshop to match up position and stuffs?

**Comment by soniyaprasad77** [comment]
Alrighty, i'm counting on you.
