### ISSUE TITLE
Scroll up bug.

### ISSUE THREAD

**Issue by AdityaKumar2408** [soniyaprasad77/soniyaprasad77.github.io#54]
**Describe the bug**
Scroll up button is visible even at the topmost position of page

**Expected behavior**
Scroll up button shouldn't visible at topmost position of page.

**Screenshots**
![image](https://github.com/soniyaprasad77/soniyaprasad77.github.io/assets/110921916/7c789fde-3944-4c61-bdd8-7ec560978b16)

**Additional context**
I will fix this and also add relevant css styling for fading of it when reaches at top position. 
@soniyaprasad77  please assign it to me sooner as deadline is near and I want to work upon it sooner

**Comment by AdityaKumar2408** [comment]
@soniyaprasad77 please respond to the messages.

**Comment by soniyaprasad77** [comment]
Yeah, you can work on this issue @AdityaKumar2408

**Comment by QuanHeMa** [comment]
Hi！I am very interested in this question. Could you assign this question to me？
