### ISSUE TITLE
Adding the "back-to-top" button the website.

### ISSUE THREAD

**Issue by RonitBaranwal** [soniyaprasad77/soniyaprasad77.github.io#7]
The Website is marvelous. The Thing which I would like to add is a "back-to-top" button which I general see in many of the websites.

This is the general UI update which I would like to add.

If its okay for you may I get assigned for it and start working on it??

**Comment by soniyaprasad77** [comment]
Yeah

**Comment by RonitBaranwal** [comment]
Please add hacktoberfest label on this issue.

**Comment by MrDBC** [comment]
can i work on this feature? @soniyaprasad77
